spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/servidores_spring
    username: root
  jpa:
    hibernate:
      ddl-auto: none # Altere para update caso queira usar o command line runner
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
